# Generated by Django 2.2.1 on 2019-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('released_date', models.DateField()),
                ('rated', models.CharField(max_length=32)),
                ('runtime', models.IntegerField()),
                ('genre', models.TextField()),
                ('director', models.TextField()),
                ('writers', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.TextField()),
                ('country', models.CharField(max_length=128)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('imdb_id', models.CharField(max_length=32)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
